name: basic-quality-check
on: pull_request

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: docker://tiangolo/latest-changes:0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: release-notes.md
          latest_changes_header: '## Latest Changes\n\n'
          debug_logs: true
