name: unit-tests
on: [push, pull_request]
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Coverage run
        run: poetry run coverage run -m pytest
      - name: Coverage report
        run: poetry run coverage report
      - name: Coverage xml
        run: poetry run coverage xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
